export const routes = [
	{
		name: 'About',
		url: 'about',
	},
	{
		name: 'Projects',
		url: 'projects',
	},
	{
		name: 'Blog',
		url: 'blog',
	},
	{
		name: 'Contact',
		url: 'contact',
	},
	{
		name: 'Guestbook',
		url: 'guestbook',
	},
];

export const allOfSkillsIhaveTried = [
	{ id: 1, name: 'HTML/CSS', isSelected: false },
	{ id: 2, name: 'Astro', isSelected: false },
	{ id: 3, name: 'Typescript', isSelected: false },
	{ id: 4, name: 'Javascript', isSelected: false },
	{ id: 5, name: 'PHP', isSelected: false },
	{ id: 6, name: 'Python', isSelected: false },
	{ id: 7, name: 'Flask', isSelected: false },
	{ id: 8, name: 'React', isSelected: false },
	{ id: 9, name: 'Redux', isSelected: false },
	{ id: 10, name: 'Sass', isSelected: false },
	{ id: 11, name: 'Tailwindcss', isSelected: false },
	{ id: 12, name: 'Node.js', isSelected: false },
	{ id: 13, name: 'Express', isSelected: false },
	{ id: 14, name: 'EJS', isSelected: false },
	{ id: 15, name: 'Three.js', isSelected: false },
	{ id: 16, name: 'GSAP', isSelected: false },
	{ id: 17, name: 'Socket.io', isSelected: false },
	{ id: 18, name: 'Googlemaps API', isSelected: false },
	{ id: 19, name: 'MySQL', isSelected: false },
	{ id: 20, name: 'MongoDB', isSelected: false },
	{ id: 21, name: 'AWS', isSelected: false },
	{ id: 22, name: 'Netlify', isSelected: false },
	{ id: 23, name: 'PaaS', isSelected: false },
	{ id: 24, name: 'Deployment', isSelected: false },
	{ id: 25, name: 'Linux', isSelected: false },
	{ id: 26, name: 'Vitest', isSelected: false },
	{ id: 27, name: 'Vue', isSelected: false },
	{ id: 28, name: 'TeamProject', isSelected: false },
];

export const allOfMyProjects = [
	{
		id: 34,
		title: "Dug's Blog",
		descriptionEn: 'A personal blog built with Astro in SSR',
		descriptionKo: 'Astro, SSR로 구현한 개인 블로그',
		descriptionJa: 'Astro、SSRで実装した個人ブログ',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsblog-frontend',
		backendRepositoryURL: '',
		period: ['2025-02-20', ''],
		skills: ['HTML/CSS', 'Astro', 'Typescript', 'Tailwindcss'],
	},
	{
		id: 33,
		title: "Dug's notes - notepad HTML",
		descriptionEn: 'A project to note ideas about HTML',
		descriptionKo: 'HTML에 관한 아이디어를 기록하는 프로젝트',
		descriptionJa: 'HTMLに対してのアイデアを記録するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-notepad-html',
		backendRepositoryURL: '',
		period: ['2025-02-18', ''],
		skills: ['HTML/CSS', 'Javascript'],
	},
	{
		id: 32,
		title: '7Javascript games',
		descriptionEn: 'A project to build 7Javascript games',
		descriptionKo: '7개의 자바스크립트 게임을 제작하는 프로젝트',
		descriptionJa: '7個のJavascriptゲームを制作するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/7javascriptgames',
		backendRepositoryURL: '',
		period: ['2025-02-16', ''],
		skills: ['HTML/CSS', 'Javascript'],
	},
	{
		id: 31,
		title: "Dug's notes - Typescript",
		descriptionEn: 'A project to learn concepts of Typescript',
		descriptionKo: 'Typescript의 개념을 배우는 프로젝트',
		descriptionJa: 'Typescriptのコンセプトを習うプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-typescript',
		backendRepositoryURL: '',
		period: ['2025-02-07', ''],
		skills: ['Typescript'],
	},
	{
		id: 30,
		title: "Dug's notes - Astro SSR by Coding in public",
		descriptionEn: 'A project to learn concepts of Astro ',
		descriptionKo: 'Astro의 개념을 배우는 프로젝트',
		descriptionJa: 'Astroのコンセプトを習うプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-astro-coding-in-public',
		backendRepositoryURL: '',
		period: ['2025-01-23', '2025-02-03'],
		skills: ['Astro'],
	},
	{
		id: 29,
		title: "Dug's notes - Astro SSR by traversymedia",
		descriptionEn: 'A project to learn concepts of Astro SSR',
		descriptionKo: 'Astro SSR의 개념을 배우는 프로젝트',
		descriptionJa: 'Astro SSRのコンセプトを習うプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-astro-ssr-by-traversymedia',
		backendRepositoryURL: '',
		period: ['2025-01-16', '2025-01-23'],
		skills: ['Astro'],
	},
	{
		id: 28,
		title: "Dug's notes - Astro by JamesQQuick",
		descriptionEn: 'A project to learn concepts of Astro',
		descriptionKo: 'Astro의 개념을 배우는 프로젝트',
		descriptionJa: 'Astroのコンセプトを習うプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-astro-by-jamesqquick',
		backendRepositoryURL: '',
		period: ['2025-01-14', '2025-01-24'],
		skills: ['Astro'],
	},
	{
		id: 27,
		title: "Dug's notes - Astro by traversymedia",
		descriptionEn: 'A project to learn concepts of Astro',
		descriptionKo: 'Astro의 개념을 배우는 프로젝트',
		descriptionJa: 'Astroのコンセプトを習うプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-astro-by-traversymedia',
		backendRepositoryURL: '',
		period: ['2025-01-12', '2025-01-13'],
		skills: ['Astro'],
	},
	{
		id: 26,
		title: "Dug's notes - Pokemon memory game",
		descriptionEn: 'A project to build a Pokemon themed HTML game',
		descriptionKo: '포켓몬이 테마인 HTML게임을 제작하는 프로젝트',
		descriptionJa: 'ポケモンがテマのHTMLゲームを制作するプロジェクト',
		deploymentURL: 'https://dugsnotes-pokemon-memory-game.netlify.app',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-pokemon-memory-game',
		backendRepositoryURL: '',
		period: ['2025-01-02', '2025-01-03'],
		skills: ['HTML/CSS', 'Javascript'],
	},
	{
		id: 25,
		title: "Dug's notes - googlemaps",
		descriptionEn: 'A project to practice manipulating Googlemaps API',
		descriptionKo: 'Googlemaps API 조작을 연습하는 프로젝트',
		descriptionJa: 'Googlemaps API操作を練習するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-googlemaps',
		backendRepositoryURL: '',
		period: ['2024-10-30', '2025-01-05'],
		skills: ['HTML/CSS', 'Javascript', 'Googlemaps API'],
	},
	{
		id: 24,
		title: 'React best practice',
		descriptionEn: 'A project to practice build React page efficiently',
		descriptionKo: '효율적인 React페이지 작성을 연습하는 프로젝트',
		descriptionJa: '効率的なReactページ作成を連取するプロジェクタ',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/reactjs-best-practice',
		backendRepositoryURL: '',
		period: ['2024-09-15', ''],
		skills: ['HTML/CSS', 'Typescript', 'React'],
	},
	{
		id: 23,
		title: '25Projects with React',
		descriptionEn: 'A project to build 25React page',
		descriptionKo: '25개의 React페이지를 제작하는 프로젝트',
		descriptionJa: '25個のReactページを制作するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/25projectswithreact',
		backendRepositoryURL: '',
		period: ['2024-07-16', ''],
		skills: ['HTML/CSS', 'Typescript', 'React', 'Sass'],
	},
	{
		id: 22,
		title: "Dug's notes - Python",
		descriptionEn: 'A project to learn concepts of Python, Flask',
		descriptionKo: 'Python과 Flask의 개념을 배우는 프로젝트',
		descriptionJa: 'PythonとFlaskのコンセプトを習うプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-python',
		backendRepositoryURL: '',
		period: ['2024-06-08', '2024-07-26'],
		skills: ['Python', 'Flask'],
	},
	{
		id: 21,
		title: "Dug's notes - three.js",
		descriptionEn: 'A project to learn concepts of three.js',
		descriptionKo: 'three.js의 개념을 배우는 프로젝트',
		descriptionJa: 'three.jsのコンセプトを習うプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-three.js',
		backendRepositoryURL: '',
		period: ['2024-06-04', ''],
		skills: ['HTML/CSS', 'Javascript', 'Three.js'],
	},
	{
		id: 20,
		title: "Dug's notes - svg",
		descriptionEn: 'A project to practice manipulate svg file on HTML',
		descriptionKo: 'HTML상의 svg파일 조작을 연습하는 프로젝트',
		descriptionJa: 'HTML上のsvgファイル操作を練習するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-svg',
		backendRepositoryURL: '',
		period: ['2024-05-24', '2024-06-04'],
		skills: ['HTML/CSS', 'Javascript'],
	},
	{
		id: 19,
		title: '10Responsive websites(HTML,CSS,Javascript)',
		descriptionEn: 'A project to build 10responsive webpsites',
		descriptionKo: '10가지 반응형 웹사이트를 제작하는 프로젝트',
		descriptionJa: '10個の反応形ウェブサイトを制作するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/10responsivewebsites-html-css-javascript',
		backendRepositoryURL: '',
		period: ['2024-05-05', '2024-06-06'],
		skills: ['HTML/CSS', 'Javascript'],
	},
	{
		id: 18,
		title: 'Cloning qude',
		descriptionEn: 'A project to project manipulating GSAP by building a clone page of Qude',
		descriptionKo: '웹사이트 Qude의 클론페이지를 제작을 통해 GSAP 조작을 연습하는 프로젝트',
		descriptionJa: 'ウェブサイトQudeのクローンページを制作を通じてGSAPを操作を練習するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/cloning-qude',
		backendRepositoryURL: '',
		period: ['2024-05-03', '2024-06-19'],
		skills: ['HTML/CSS', 'Javascript', 'GSAP'],
	},
	{
		id: 17,
		title: "Dug's notes - GSAP",
		descriptionEn: 'A project to practice building components using GSAP',
		descriptionKo: 'GSAP을 활용해 컴포넌트 제작을 연습하는 프로젝트',
		descriptionJa: 'GSAPを活用してコンポーネント制作を練習するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-gsap',
		backendRepositoryURL: '',
		period: ['2024-04-29', '2024-05-03'],
		skills: ['HTML/CSS', 'Javascript', 'GSAP'],
	},
	{
		id: 16,
		title: '150Animation projects(HTML,CSS,Javascript)',
		descriptionEn: 'A project to build 150 HTML animations',
		descriptionKo: '150가지 HTML 애니메이션을 제작하는 프로젝트',
		descriptionJa: '150個のHTMLアニメーションを制作するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/150animationprojects-html-css-javascript',
		backendRepositoryURL: '',
		period: ['2024-02-12', '2024-07-06'],
		skills: ['HTML/CSS', 'Javascript'],
	},
	{
		id: 15,
		title: "Dug's blog(prototype)",
		descriptionEn: 'A project to build a SSR blog page',
		descriptionKo: 'SSR블로그 페이지를 제작하는 프로젝트',
		descriptionJa: 'SSRブログページを制作するプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: '',
		backendRepositoryURL: 'https://github.com/duglikespiano/dugsblog',
		period: ['2024-02-02', '2024-09-06'],
		skills: ['HTML/CSS', 'Typescript', 'Sass', 'Node.js', 'Express', 'EJS'],
	},
	{
		id: 14,
		title: "Dug's notes - PHP",
		descriptionEn: 'A project to learn concepts of PHP',
		descriptionKo: 'PHP의 개념을 배우는 프로젝트',
		descriptionJa: 'PHPのコンセプトを習うプロジェクト',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-php',
		backendRepositoryURL: '',
		period: ['2024-01-01', ''],
		skills: ['PHP'],
	},
	{
		id: 13,
		title: '60Projects In 60Days(HTML,CSS,Javascript)',
		descriptionEn: 'Coding challenges for 60 days with HTML,CSS,Javascript',
		descriptionKo: 'HTML,CSS,Javascript를 통한 60일간의 Coding challenge',
		descriptionJa: 'HTML、CSS、Javascriptを通じた60日間のCoding challenge',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/60projectsin60days-html-css-javascript',
		backendRepositoryURL: '',
		period: ['2023-12-09', '2024-02-06'],
		skills: ['HTML/CSS', 'Javascript'],
	},
	{
		id: 12,
		title: "Dug's notes - Node.js",
		descriptionEn: 'Mastering backend knowledge through Node.js',
		descriptionKo: 'Node.js를 통한 백엔드 관련 지식 습득',
		descriptionJa: 'Node.jsを通じたバックエンド関連知識の習得',
		deploymentURL: '',
		frontendRepositoryURL: '',
		backendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-node.js',
		period: ['2023-11-01', ''],
		skills: ['Javascript', 'Node.js', 'MySQL', 'MongoDB', 'Socket.io'],
	},
	{
		id: 11,
		title: '50Projects In 50Days(HTML,CSS,Javascript)',
		descriptionEn: 'Coding challenges for 50 days with HTML,CSS,Javascript',
		descriptionKo: 'HTML,CSS,Javascript를 통한 50일간의 Coding challenge',
		descriptionJa: 'HTML、CSS、Javascriptを通じた50日間のCoding challenge',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/50projectsin50days-html-css-javascript',
		backendRepositoryURL: '',
		period: ['2023-10-31', '2023-12-08'],
		skills: ['HTML/CSS', 'Javascript'],
	},
	{
		id: 10,
		title: "Dug's Works",
		descriptionEn: "A website to introduce Dug's works and contact with Dug",
		descriptionKo: 'Dug의 작품 소개를 위한 웹 사이트',
		descriptionJa: 'Dugの作品紹介の為のウェブサイト',
		deploymentURL: 'https://dugsworks.netlify.app',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsworks-frontend',
		backendRepositoryURL: 'https://github.com/duglikespiano/dugsworks-backend',
		period: ['2023-09-30', ''],
		skills: [
			'HTML/CSS',
			'Typescript',
			'React',
			'Redux',
			'Sass',
			'Node.js',
			'Express',
			'MySQL',
			'AWS',
			'Netlify',
			'PaaS',
			'Deployment',
			'Linux',
		],
	},
	{
		id: 9,
		title: "Dug's notes - Algorithms and Data Structure",
		descriptionEn: 'Mastering Algorithms and Data Structure with Javascript',
		descriptionKo: 'Javascript를 통한 알고리즘 및 자료구조 관련 지식 습득',
		descriptionJa: 'Javascriptを通じたアルゴリズム及び資料構造関連知識習得',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-algorithms-datastructures-javascript',
		backendRepositoryURL: 'https://github.com/duglikespiano/dugsnotes-algorithms-datastructures-javascript',
		period: ['2023-09-12', '2023-09-15'],
		skills: ['Javascript'],
	},
	{
		id: 8,
		title: "Dug's notes - UnitTesting",
		descriptionEn: 'Writing test codes with vitest(Typescript, Javascript)',
		descriptionKo: 'Vitest(Typescript, Javascript)를 통한 test code 작성연습',
		descriptionJa: 'Vitest(Typescript, Javascript)を通じたtest codeの作成練習',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/dugesnotes-unittesting-typescript',
		backendRepositoryURL: 'https://github.com/duglikespiano/dugesnotes-unittesting-typescript',
		period: ['2023-08-26', '2023-09-15'],
		skills: ['Typescript', 'Javascript', 'Vitest'],
	},
	{
		id: 7,
		title: '100Day of Code(Python)',
		descriptionEn: 'Coding challenges for 100 days with Python',
		descriptionKo: 'Python을 통한 100일간의 Coding challenge',
		descriptionJa: 'Pythonを通じた100日間のCoding challenge',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/100daysofcode-python',
		backendRepositoryURL: 'https://github.com/duglikespiano/100daysofcode-python',
		period: ['2023-08-25', '2023-11-03'],
		skills: ['Python'],
	},
	{
		id: 6,
		title: 'Social Login Collector',
		descriptionEn: "A website to practice big platforms' social logins API",
		descriptionKo: '대형 플랫폼들의 Social login API를 다루는 웹 사이트',
		descriptionJa: '大きなプラットフォームのSocial login APIのhandlingを練習',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/sociallogincollector-frontend',
		backendRepositoryURL: 'https://github.com/duglikespiano/sociallogincollector-backend',
		period: ['2023-06-09', '2023-06-23'],
		skills: ['HTML/CSS', 'Typescript', 'React', 'Node.js', 'Express'],
	},
	{
		id: 5,
		title: 'Chat with Dug',
		descriptionEn: 'A website to have a chat with friends with Socket.io',
		descriptionKo: '친구들과 사용하기 위해 만든 Socket.io를 활용한 채팅 사이트',
		descriptionJa: '友達を使用する為のSocket.ioを活用したチャットサイト',
		deploymentURL: 'https://chatwithdug.netlify.app',
		frontendRepositoryURL: 'https://github.com/duglikespiano/chatwithdug-frontend',
		backendRepositoryURL: 'https://github.com/duglikespiano/chatwithdug-backend',
		period: ['2023-03-01', '2023-04-27'],
		skills: [
			'HTML/CSS',
			'Javascript',
			'React',
			'Socket.io',
			'Node.js',
			'Express',
			'MySQL',
			'AWS',
			'Netlify',
			'PaaS',
			'Deployment',
			'Linux',
		],
	},
	{
		id: 4,
		title: 'Drag&Drop',
		descriptionEn: "A component to practice DOM's Drag&Drop with Vue",
		descriptionKo: 'Vue를 사용하여 DOM의 Drag&Drop을 구현한 컴포넌트',
		descriptionJa: 'Vueを使用してDOMのDrag&Dropを具現したコンポーネント',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/draganddrop-frontend',
		backendRepositoryURL: 'https://github.com/duglikespiano/draganddrop-backend',
		period: ['2023-02-20', '2023-03-03'],
		skills: ['HTML/CSS', 'Javascript', 'Vue', 'Node.js', 'Express', 'MySQL'],
	},
	{
		id: 3,
		title: 'TodoList',
		descriptionEn: 'A Todo list component with basic React',
		descriptionKo: 'React의 기초적인 문법을 활용하여 구현한 Todo list 컴포넌트',
		descriptionJa: 'Reactの基礎文法を活用して具現したコンポーネント',
		deploymentURL: '',
		frontendRepositoryURL: 'https://github.com/duglikespiano/todolist-frontend',
		backendRepositoryURL: 'https://github.com/duglikespiano/todolist-backend',
		period: ['2023-01-09', '2023-01-15'],
		skills: ['HTML/CSS', 'Javascript', 'Node.js', 'Express', 'MySQL'],
	},
	{
		id: 2,
		title: 'Jegabox',
		descriptionEn: 'A Clone site of Megabox(Korean movie theater)',
		descriptionKo: '메가박스 웹 사이트의 클론사이트',
		descriptionJa: '韓国の映画館、MEGABOXウェブサイトのクロンサイト',
		deploymentURL: '',
		frontendRepositoryURL: '',
		backendRepositoryURL: 'https://github.com/duglikespiano/justcode-7-2nd-jegabox-back',
		period: ['2022.11.14', '2022.11.25'],
		skills: ['Node.js', 'Javascript', 'Express', 'MySQL', 'TeamProject'],
	},
	{
		id: 1,
		title: 'Photofolio',
		descriptionEn: "A Clone site of Grafolio(Korean creators' playground)",
		descriptionKo: '그라폴리오 웹 사이트의 클론사이트',
		descriptionJa: '韓国のクリエイター向けのサイト、Grafolioのクロンサイト',
		deploymentURL: '',
		frontendRepositoryURL: '',
		backendRepositoryURL: 'https://github.com/duglikespiano/justcode-7-1st-photofolio-renewal-back',
		period: ['2022-10-31', '2022-11-11'],
		skills: ['Node.js', 'Javascript', 'Express', 'MySQL', 'TeamProject'],
	},
];

export type ProjectObjectType = {
	id: number;
	title: string;
	descriptionEn: string;
	descriptionKo: string;
	descriptionJa: string;
	deploymentURL: string;
	frontendRepositoryURL: string;
	backendRepositoryURL: string;
	period: string[];
	skills: string[];
};

export const allofMySkills = {
	frontend: [
		{ id: 1, name: 'HTML/CSS' },
		{ id: 2, name: 'Astro' },
		{ id: 3, name: 'React' },
		{ id: 4, name: 'Redux' },
		{ id: 5, name: 'Vue' },
		{ id: 6, name: 'Sass' },
		{ id: 7, name: 'Javascript' },
		{ id: 8, name: 'Typescript' },
		{ id: 9, name: 'TailwindCSS' },
	],
	backend: [
		{ id: 1, name: 'Node.js' },
		{ id: 2, name: 'Express' },
		{ id: 3, name: 'PHP' },
		{ id: 4, name: 'Python' },
		{ id: 5, name: 'MySQL' },
		{ id: 6, name: 'MongoDB' },
		{ id: 7, name: 'Socket.io' },
		{ id: 8, name: 'Javascript' },
		{ id: 9, name: 'Typescript' },
	],
	cloud: [
		{ id: 1, name: 'AWS' },
		{ id: 2, name: 'Railway' },
		{ id: 3, name: 'Netlify' },
		{ id: 4, name: 'CloudType' },
	],
	misc: [
		{ id: 1, name: 'Git' },
		{ id: 2, name: 'Linux' },
		{ id: 3, name: 'Public APIs' },
		{ id: 4, name: 'Vitest' },
	],
};
